/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jlox;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/*
    Way back when computers were as big as Winnebagos but had less memory than your watch,
    some people used “scanner” only to refer to the piece of code that dealt with reading
    raw source code characters from disk and buffering them in memory. Then “lexing” was
    the subsequent phase that did useful stuff with the characters.

 */
public class Lox {
    private static final Interpreter interpreter = new Interpreter();
    static boolean hadError = false;
    static boolean hadRuntimeError = false;
    static PrintStream err = System.err;

    public static void main1(String[] args) throws IOException {
        var argCount = args.length;

        if (argCount > 1) {
            System.out.println("Usage: jlox [script]");
            System.exit(Sysexits.EX_USAGE);
        } else if (argCount == 1) {
            runScript(args[0]);
        } else {
            runPrompt();
        }
    }

    public static void main(String[] args) throws IOException {
        //runScript("C:\\stuff\\java\\jlox\\app\\src\\test.lox");
        runScript("/Users/pafau/IdeaProjects/jlox/app/src/test.lox");
    }

    static void runScript(String fileName) throws IOException {
        Path scriptPath = getScriptPath(fileName);
        String scriptContents = Files.readString(scriptPath, Charset.defaultCharset());

        run(scriptContents);
        if (hadError) System.exit(Sysexits.EX_DATAERR);
        if (hadRuntimeError) System.exit(Sysexits.EX_SOFTWARE);
    }

    static void run(String loxSource) {
        System.out.println("source: " + loxSource);
        var scanner = new Scanner(loxSource);
        var tokens = scanner.scanTokens();
        var parser = new Parser(tokens);
        var program = parser.parse();

        if (hadError) return;

        interpreter.interpret(program);

//        for (var token : tokens) {
//            System.out.println(token);
//        }
    }

    private static Path getScriptPath(String fileName) {
        var path = Paths.get(fileName);
        verifyScriptFileExistsOrDie(path);

        return path;
    }

    private static void verifyScriptFileExistsOrDie(Path scriptPath) {
        if (Files.notExists(scriptPath) || !Files.isRegularFile(scriptPath)) {
            System.out.println(scriptPath + " doesn't exist or is a directory");
            System.exit(Sysexits.EX_NOINPUT);
        }
    }

    static void error(Token token, String message) {
        if (token.type == TokenType.EOF) {
            report(token.line, " at end", message);
        } else {
            report(token.line, " at '" + token.lexeme + "'", message);
        }
    }

    static void error(int line, String message) {
        report(line, "", message);
    }

    static void runtimeError(RuntimeError e) {
        err.println(e.getMessage() + "\n[line " + e.token.line + "]");
        hadRuntimeError = true;
    }

    private static void report(int line, String where, String message) {
        err.printf("[line %s] Error%s: %s\n", line, where, message);
        hadError = true;
    }

    static void setErr(PrintStream err) {
        Lox.err = err;
    }

    static void runPrompt() throws IOException {
        var isr = new InputStreamReader(System.in);
        var reader = new BufferedReader(isr);

        System.out.println("-=[ Welcome to Lox prompt. To quit, type 'bye()<ENTER>' or press ctrl-d");
        for (; ; ) {
            System.out.print("> ");
            var line = reader.readLine();
            if (line == null || "bye()".equals(line)) {
                System.out.println("exit signal received, quitting");
                break;
            }
            run(line);
            hadError = false;
        }
    }
}
